<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title>Legal</title>
		<link rel="stylesheet" type="text/css" href="css/static.css">
	</head>

	<body>

	<?php
		require 'navigation.php'
	?>

		<div class="staticText" id="legalText">
			<h1> Legal </h1>
			<h2 class="heading-title page-title">Terms &amp; Conditions</h2>
			<article id="post-1673" class="post-1673 page type-page status-publish hentry instock">
				<div class="entry-content-post">
				<p><b>1. Acceptance of Terms</b></p>
				<p>Wireless Audio Solutions, LLC, a New York limited liability corporation (referred to as “Company,” “us” or “we”), provides the Party Headphones website (http://partyheadphones.com) (all subdomains to the website collectively referred to as the “Site”), as well as products and services related to audio equipment, headphones and other hardware and related leasing and sales of same (collectively referred to as “Offerings”), subject to your compliance with the following Terms and Conditions of Use (“Terms”), as well as any other written agreement(s) between us and you.</p>
				<p>We reserve the right to change these Terms from time to time with or without notice to you. You acknowledge and agree that it is your responsibility to periodically review this Site and these Terms. Your continued use of this Site and Offerings after such modifications will constitute acknowledgement and acceptance of the modified Terms.</p>
				<p>As used in these Terms, references to our “Affiliates” include our owners, licensees, assigns, subsidiaries, affiliated companies, officers, directors, suppliers, partners, sponsors, advertisers, and includes (without limitation) all parties involved in creating, producing, and/or delivering this Site and/or contents and Offerings available on this Site.</p>
				<p>BY USING THIS SITE AND OFFERINGS ON THIS SITE, YOU AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT WISH TO BE BOUND BY THE THESE TERMS, PLEASE EXIT THE SITE. YOUR SOLE REMEDY FOR DISSATISFACTION WITH THIS SITE, PRODUCTS, OFFERINGS OR OFFERINGS AVAILABLE ON THIS SITE, OR THESE TERMS IS TO CEASE USING THE SITE AND/OR THOSE PARTICULAR PRODUCTS, OFFERINGS OR OFFERINGS. THESE TERMS ARE EFFECTIVE ONCE YOU CLICK THE ‘I AGREE’ BUTTON BELOW.</p>
				<p><b>2. Offerings</b></p>
				<p>Offerings. Company provides a number of Offerings for users on its Site.</p>
				<p>No Guarantee. Although Company works hard to provide quality Offerings, you understand and acknowledge that we cannot promise or guarantee specific results from using the Site or Offerings available on this site.</p>
				<p>Temporary Interruptions. You understand and agree that temporary interruptions of the Site may occur as normal events that are out of our control. You also understand and agree that we have no control over the third-party networks or service(s) that we may use to provide you with Offerings. You agree that the Offerings available on this Site are provided “AS IS” and that we assume no responsibility for the timeliness, deletion, mis-delivery or failure to store any user communications or personalization settings.</p>
				<p><b>3. Payment</b></p>
				<p>Fees. If you choose to purchase one or more of the Offerings provided on our Site, you agree to pay all fees associated with the Offerings.</p>
				<p>This site does not process credit cards, or take other payment processing information. Payment processing is handled through third-party services, which are contracted with by the Company and subject to change at the Company’s discretion. The Company currently uses Flagship Merchant Services, with authorize.net. In the event you sign up for a Service that is ongoing and incurs reoccurring charges (such as a subscription), such charges will be billed in advance of service.</p>
				<p>Overdue Amounts. If, for any reason, your credit card company declines or otherwise refuses to pay the amount owed for the Offerings you have purchased, you agree that we may, at our option, suspend or terminate performance of Offerings or delivery of products and may require you to pay any overdue amounts incurred (including any third-party chargeback fees or penalties) by other means acceptable to us. In the event legal action is necessary to collect on balances due, you agree to reimburse us for all expenses incurred to recover sums due, including attorney fees and other legal expenses.</p>
				<p><b>4. Site Conduct, Posting Policies &amp;Third Party Websites</b></p>
				<p>User-Created Content Guidelines: Your use of the Siteis subject to all applicable laws and regulations, and you are solely responsible for any comments or posts you leave on the Site or the Blog. By posting information on the Site, or by otherwise using any communications service, message board, newsgroup, or other interactive service available on the Site, you agree that you will not post comments, messages, links, code or other information that:</p>
				<p>i. is unlawful, threatening, abusive, harassing, defamatory, deceptive, fraudulent, invasive of another’s privacy, or includes graphic descriptions of sexual or violent content;</p>
				<p>ii. victimizes, harasses, degrades, or intimidates an individual or group of individuals on the basis of religion, gender, sexual orientation, race, ethnicity, age, or disability;</p>
				<p>iii. infringes on any patent, trademark, trade secret, copyright, right of publicity, or other proprietary right of any party;</p>
				<p>iv. consists of unsolicited advertising, junk or bulk email (also known as “spam”), chain letters, any other form of unauthorized solicitation, or any form of lottery or gambling;</p>
				<p>v. contains any form of malicious code, files, or programs that are designed or intended to disrupt, damage, or limit the functionality of any software, hardware, or telecommunications equipment or otherwise causes damage, or allows you to obtain unauthorized access to any data or other information of any third party;</p>
				<p>vi. breaches the security of, compromises or otherwise allows access to secured, protected or inaccessible areas of this Site, or attempts to gain access to other network or server via your account on this Site;</p>
				<p>vii. impersonates any person or entity, including any of our employees or representatives.</p>
				<p>No Endorsement. Company neither endorses nor assumes any liability for any material uploaded or submitted by users on any part of the Site. Although we do not pre-screen, police or monitor comments posted on the Site, we and our agents reserve the right to remove any and all postings that we feel do not comply with these Terms and any other rules of user conduct for our Site, or are otherwise harmful, objectionable, or inaccurate. We are not responsible for any failure or delay in removing such postings.</p>
				<p>Third-Party Sites and Information. This Site may redirect or link to other websites on the Internet, or may otherwise include references to information, products or services made available by unaffiliated third parties. While we make every effort to work with trusted, reputable providers, from time to time such sites may contain information, material or policies that some may find inappropriate or personally objectionable. You understand that we are not responsible for the accuracy, completeness, decency or legality of content hosted by third party websites, nor are we responsible for errors or omissions in any references made on those websites. The inclusion of such a link or reference is provided merely as a convenience and does not imply endorsement of, or association with the Site or party by us, or any warranty of any kind, either express or implied.</p>
				<p>Promotions. From time to time, this Site may include advertisements offered by third parties. You may enter into correspondence with or participate in promotions of the advertisers showing their products on this site. Any such correspondence or promotions, including the delivery of and the payment for goods and services by those third parties, and any other terms, conditions, warranties or representations associated therewith, are solely between you and the advertiser. We assume no liability, obligation or responsibility for any part of any such correspondence or promotion.</p>
				<p><b>5. Company Intellectual Property</b></p>
				<p>Content. For purposes of these Terms, “content” is defined as any information, communications, software, published works, photos, video, graphics, music, sounds, or other material that can be viewed by users on our Site and is owned by Company or its Affiliates.</p>
				<p>Ownership of Content. By accepting these Terms, you agree that all content presented to you on this Site is protected by any and all intellectual property and/or other proprietary rights available within the United States, and is the sole property of Company or its Affiliates.</p>
				<p>All custom graphics, icons, logos and service names are registered trademarks, trademarks or service marks of Company Inc. or its Affiliates. All other trademarks or service marks are property of their respective owners. Nothing in these Terms of Use grants you any right to use any trademark, service mark, logo, and/or the name of Company Inc. or its Affiliates.</p>
				<p>Certain of the ideas, software and processes incorporated into the Offerings available on this Site are protected by patent applications pending in the United States, and we intend to prepare and file additional patent applications in selected foreign jurisdictions.</p>
				<p>Limitations on Use of Content. Except for a single copy made for personal use, you may not copy, reproduce, modify, republish, upload, post, transmit, or distribute any content from this Site in any form or by any means whatsoever without prior written permission from us. Any unauthorized use of Site content violates our intellectual property interests and could result in criminal or civil penalties.</p>
				<p>No warranty for Third-Party Infringement. Neither we or our Affiliates warrant or represent that your use of materials displayed on, or obtained through, this Site will not infringe the rights of third parties.</p>
				<p><b>6. Content You Create.</b></p>
				<p>Your Intellectual Property Rights. Subject to our Privacy Policy (located on the Site), any communication or material that you transmit to this Site or to us, whether by email or other means, for any reason, will be treated as non-confidential and non-proprietary user content (“User Content”). While you retain all rights to the User Content, you grant us (including our employees and Affiliates), a non-exclusive, paid-up, perpetual, and worldwide right to copy, distribute, display, publish, translate, adapt, modify, and otherwise use the User Content for any purpose whatsoever, regardless of the form or medium in which it is used.</p>
				<p>We respect the intellectual property rights of others, and we ask you to do the same. In instances where we are notified of alleged infringing Company-or User Content through our Designated Agent, a decision may be made to remove access or disable access to such materials, in compliance with the safe harbor provisions of the Digital Millennium Copyright Act, 17 U.S.C. § 512(c). We may also make a good faith attempt to contact the person who submitted the affected material so that they may make a counter-notification.</p>
				<p>If you believe that you or someone else’s copyright has been infringed by Company-or User Content provided on this Site, you (or the owner or rights holder, collectively, “Rights Holder”) should send notification to our Designated Agent immediately. Prior to sending us notice, the Rights Holder may wish to consult a lawyer to determine their rights and legal obligations under the DMCA and any other applicable laws. Nothing here or anywhere on this Site is intended as a substitute for qualified legal advice. To file a Notice of Infringing Material, we ask that the Rights Holder provide the following information:</p>
				<p>1. Reasonably sufficient details about the nature of the copyrighted work in question, or, in the case of multiple alleged infringements, a representative list of such works. This should include, title(s), author(s), any U.S. Copyright Registration number(s), URL(s) etc.;</p>
				<p>2. Reasonably sufficient details to enable us to identify and locate the material that is allegedly infringing the Rights Holders’ work(s) (for example, file name or URL of the page(s) that contain(s) the material);</p>
				<p>3. The Rights Holder’s contact information so that we can contact them (including for example, the Rights Holder’s address, telephone number, and email address);</p>
				<p>4. A statement that the Rights Holder has a good faith belief that the use of the material identified above in 2 is not authorized by the copyright owner, its agent, or the law;</p>
				<p>5. A statement, under penalty of perjury, that the information in the notification is accurate and that the Rights Holder is authorized to act on behalf of the copyright owner; and</p>
				<p>6. The Rights Holder’s electronic signature.</p>
				<p> Notice may be sent to:</p>
				<p>By Mail:<br>
				Wireless Audio Solutions, LLC<br>
				407 College Avenue, PMB 300<br>
				Ithaca, New York 14850<br>
				Attn: DMCA Agent<br>
				By e-mail: <a href="mailto:support@partyheadphones.com">support@partyheadphones.com </a></p>
				<p> Counter-Notification. If material that you have posted to our Site has been taken down, you may file a counter-notification that contains the following details:</p>
				<p>1. Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;</p>
				<p>2. A statement, under penalty of perjury, that you have a good faith belief that the material was removed or disabled as a result of mistake or misidentification of the material in question;</p>
				<p>3. Your name, address and telephone number;</p>
				<p>4. A statement that you consent to the jurisdiction of the state courts or federal district court in the State of New York, Onondaga County, and that you will accept service of process from the person who provided notification in compliance with section 512 (c)(1)(C) of the DMCA, or an agent of such person.</p>
				<p>5. Your physical or electronic signature.</p>
				<p> Notice may be sent to:</p>
				<p>By Mail:<br>
				Wireless Audio Solutions, LLC<br>
				407 College Avenue, PMB 300<br>
				Ithaca, New York 14850<br>
				Attn: DMCA Agent<br>
				By e-mail: <a href="mailto:support@partyheadphones.com">support@partyheadphones.com </a></p>
				<p> You also acknowledge and agree that upon receipt of a notice of a claim of copyright infringement, we may temporarily or permanently remove the identified materials from our site without liability to you or any other party.</p>
				<p>Confidential Information. As stated above, all communications sent by you to us will be treated as non-confidential and non-proprietary (subject to our privacy policy). Please do not submit confidential or proprietary information to us (including patentable ideas, new content suggestions or business proposals) unless we have mutually agreed in writing otherwise. Ideas that we receive unsolicited will be treated as property owned by the Company and will not be returned to you.</p>
				<p><b>7. Email Services &amp; Data Stored on Our Servers</b></p>
				<p>Email Service. We may make email services available to users of our Site, either directly or through a third-party provider. We will not inspect or disclose the contents of private email messages except with the consent of the sender or the recipient, or in the narrowly-defined situations provided under the Electronic Communications Privacy Act, 18 U.S.C. § 2510, et. seq. or as other required by law or by court or governmental order. Further information is available in our Privacy Policy.</p>
				<p>Spam Prevention. We use automated tools or techniques to protect our users from mass unsolicited mailings (also known as “spam”) and/or other types of malicious or harmful content. However, such tools or techniques are not perfect, and we therefore are not responsible in cases where legitimate communications are accidentally blocked, or unsolicited communications get through to your Company supplied email account.</p>
				<p>Storage Provided by Us. While If you opt to store personal data of any kind on our servers, you understand and agree to abide by our general practices and limits concerning use of the Offerings available on our Site, including without limitation the maximum number of days that uploaded content will be retained, the maximum disk space that will be allotted, and the maximum number of times you may access the services in a given period of time. You agree that we have no responsibility or liability for the deletion or failure to store any content maintained or transmitted on or through this Site. You acknowledge that we reserve the right to remove or terminate accounts which have not paid a subscription fee (if applicable), that remain inactive for longer than one hundred twenty (120) days, or in cases where you have violated one or more terms of this Agreement.</p>
				<p><b>8. Privacy &amp; Security</b></p>
				<p>Login Required. In order to access some of the Offerings on this site, or to post User Content, you may be asked to set up an account and password. Our account registration page requests certain personal information from you (“Registration Info”). You will have the ability to maintain and periodically update your Registration Info as you see fit. By registering, you agree that all information provided by you as Registration Info is true and accurate and that you will maintain and update this information as required in order to keep it current, complete and accurate.</p>
				<p>Passwords &amp; Security. If you register for an account on the Site, you agree that you are responsible for maintaining the security and confidentiality of your password, and that you are fully responsible for all activities or charges that are incurred under your account. Therefore, you must take reasonable steps to ensure that others do not gain access to your password and account. Our employees will never ask you for your password.</p>
				<p>Disclosure to Third Party Affiliates. You hereby grant us the right to disclose to third parties certain Registration Info about you. The information we obtain through your use of this site, including your Registration Info, is subject to our Privacy Policy, which is specifically incorporated by reference into these Terms of Use.</p>
				<p><b>9. Disclaimer</b></p>
				<p>ALL CONTENT AND OFFERINGS ON THIS SITE ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, OR THE WARRANTY OF NON-INFRINGEMENT. WITHOUT LIMITING THE FOREGOING, WE MAKE NO WARRANTY THAT (A) THE CONTENT OR OFFERINGS WILL MEET YOUR REQUIREMENTS, (B) THE CONTENT, OFFERINGS OR SITE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (C) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE CONTENT OR OFFERINGS OFFERED WILL BE EFFECTIVE, ACCURATE OR RELIABLE, OR (D) THE QUALITY OF ANY CONTENT OR OFFERINGS PURCHASED OR OBTAINED BY YOU FROM THE SITE FROM US OR OUR AFFILIATES WILL MEET YOUR EXPECTATIONS OR BE FREE FROM MISTAKES, ERRORS OR DEFECTS.</p>
				<p>THIS SITE COULD INCLUDE TECHNICAL OR OTHER MISTAKES, INACCURACIES OR TYPOGRAPHICAL ERRORS. WE MAY MAKE CHANGES TO THE CONTENT AND OFFERINGS AT THIS SITE, INCLUDING THE PRICES AND DESCRIPTIONS OF ANY PRODUCTS OR OFFERINGS LISTED HEREIN, AT ANY TIME WITHOUT NOTICE. THE CONTENT OR PRODUCTS AVAILABLE AT THIS SITE MAY BE OUT OF DATE, AND WE MAKE NO COMMITMENT TO UPDATE SUCH CONTENT OR PRODUCTS.</p>
				<p>THE USE OF THE OFFERINGS OR THE DOWNLOADING OR OTHER ACQUISITION OF ANY PRODUCTS OR CONTENT THROUGH THIS SITE IS DONE AT YOUR OWN DISCRETION AND RISK AND WITH YOUR AGREEMENT THAT YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM SUCH ACTIVITIES.</p>
				<p>Through your use of the Site, you may have the opportunities to engage in commercial transactions with other users and vendors. You acknowledge that all transactions relating to any products or Offerings provided by any third party, including, but not limited to the purchase terms, payment terms, warranties, guarantees relating to such transactions, are agreed to solely between the seller of such merchandise and you.</p>
				<p>WE MAKE NO WARRANTY REGARDING ANY TRANSACTIONS EXECUTED THROUGH A THIRD PARTY, OR IN CONNECTION WITH THIS SITE, AND YOU UNDERSTAND AND AGREE THAT SUCH TRANSACTIONS ARE CONDUCTED ENTIRELY AT YOUR OWN RISK. ANY WARRANTY THAT IS PROVIDED IN CONNECTION WITH ANY OFFERINGS OR CONTENT AVAILABLE ON OR THROUGH THIS SITE FROM A THIRD PARTY IS PROVIDED SOLELY BY SUCH THIRD PARTY, AND NOT BY US OR ANY OTHER OF OUR AFFILIATES.</p>
				<p>WE RESERVE THE SOLE RIGHT TO EITHER MODIFY OR DISCONTINUE THE SITE, INCLUDING ANY OFFERINGS OR FEATURES THEREIN, AT ANY TIME WITH OR WITHOUT NOTICE TO YOU. WE SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY SHOULD WE EXERCISE SUCH RIGHT. MODIFICATIONS MAY INCLUDE, BUT ARE NOT LIMITED TO, CHANGES IN THE PRICING STRUCTURE, THE ADDITION OF FREE OR FEE-BASED SERVICES, OR CHANGES TO LIMITATIONS ON ALLOWABLE CONTENT, FILE SIZES OR FILE TYPES. ANY NEW FEATURES THAT AUGMENT OR ENHANCE THE THEN-CURRENT OFFERINGS ON THIS SITE SHALL ALSO BE SUBJECT TO THESE TERMS OF USE.</p>
				<p>SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF CERTAIN WARRANTIES, SO SOME OF THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. PLEASE CONSULT THE LAWS IN YOUR JURISDICTION.</p>
				<p><b>10. Limitation of Liability &amp; Indemnification</b></p>
				<p>Your exclusive remedy and our entire liability, if any, for any claims arising out of these Terms and your use of this Site shall be limited to the amount you paid us for Offerings purchased on the Site during the three (3) month period before the act giving rise to the liability.</p>
				<p>IN NO EVENT SHALL WE OR OUR AFFILIATES BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY SPECIAL, PUNITIVE, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND, OR ANY DAMAGES WHATSOEVER, INCLUDING, WITHOUT LIMITATION, THOSE RESULTING FROM LOSS OF USE, DATA OR PROFIT LOSS, WHETHER OR NOT WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND ON ANY THEORY OF LIABILITY, ARISING OUT OF OR IN CONNECTION WITH THE USE OF THIS SITE OR OF ANY WEBSITE REFERENCED OR LINKED TO FROM THIS SITE.</p>
				<p>FURTHER, WE SHALL NOT BE LIABLE IN ANY WAY FOR THIRD PARTY PROMISES REGARDING OUR OFFERINGS OR CONTENT OR FOR ASSISTANCE IN CONDUCTING COMMERCIAL TRANSACTIONS WITH THE THIRD PARTY THROUGH THIS SITE, INCLUDING WITHOUT LIMITATION THE PROCESSING OF ORDERS.</p>
				<p>SOME JURISDICTIONS PROHIBIT THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, SO THE ABOVE LIMITATIONS MAY NOT APPLY TO YOU. PLEASE CONSULT THE LAWS IN YOUR JURISDICTION.</p>
				<p>You agree to defend, indemnify, and hold us and our Affiliates harmless from all liabilities, claims, and expenses, including attorneys’ fees that may arise from your use or misuse of this Site. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will cooperate with us in asserting any available defenses.</p>
				<p><b>11. Termination of Use</b></p>
				<p>Grounds for Termination. You agree that we may, at our sole discretion, terminate or suspend your access to all or part of the Site with or without notice and for any reason, including, without limitation, breach of these Terms. Any suspected fraudulent, abusive or illegal activity may be grounds for barring your access to this Site, and reporting you to the proper authorities, if necessary.</p>
				<p>No Right to Offerings Upon Termination. Upon termination and regardless of the reason(s) motivating such termination, your right to use the Offerings available on this Site will immediately cease. We shall not be liable to you or any third party for any claims for damages arising out of any termination or suspension or any other actions taken by us in connection therewith. Sections 1 and 3-11 of these Terms, as well as your liability for any unpaid fees, shall survive any termination.</p>
				<p><b>12. Miscellaneous Provisions</b></p>
				<p>International Use. Although this Site may be accessible worldwide, we make no representation that materials on this Site are appropriate or available for use in locations outside the United States. Those who choose to access this Site from other locations do so on their own initiative and at their own risk. If you choose to access this Site from outside the United States, you are responsible for compliance with local laws in your jurisdiction, including but not limited to, the taxation of products purchased over the Internet. Any offer for any product, Service, and/or information made in connection with this Site is void where prohibited.</p>
				<p>Governing Law. This Site (excluding any Third Party websites) is controlled by us from our offices in the State of New York, and the statutes and laws of the State of New York shall be controlling, without regard to the conflicts of laws principles thereof. You agree and hereby submit to the exclusive personal jurisdiction and venue of the Supreme Court of the State of New York, Onondaga County or the U.S. District Court for the Northern District of New York with respect to such matters controlled by that court.</p>
				<p>Notices. All notices to a party shall be in writing and shall be made either via email or conventional mail. Notices to us must be sent to the attention of Customer Service at support@headphoneevents.com, if by email, or to our address at Headphone Events, Inc., 407 College Avenue PMB 300, Ithaca, New York 14850, if by conventional mail. You agree to allow us to submit notices to you either through the email address provided, or to the address we have on record. Any notices or communication under these Terms will be deemed delivered to the party receiving such communication (1) on the delivery date if delivered personally to the party; (2) two business days after deposit with a commercial overnight carrier, with written verification of receipt; (3) five business days after the mailing date, if sent by U.S. mail, return receipt requested; (4) on the delivery date if transmitted by confirmed facsimile; or (5) on the delivery date if transmitted by confirmed email.</p>
				<p>No Resale Right. You agree not to sell, resell, reproduce, duplicate, distribute, copy or use for any commercial purposes any portion of this Site, or use of or access to this Site or Offerings provided through this Site, beyond the limited rights granted to you under Section 5 of these Terms.</p>
				<p>Force Majeure. In addition to any excuse provided by applicable law, we shall be excused from liability for non-delivery or delay in delivery of products and Offerings available through our Site arising from any event beyond our reasonable control, whether or not foreseeable by either party, including but not limited to: labor disturbance, war, fire, accident, adverse weather, inability to secure transportation, governmental act or regulation, and other causes or events beyond our reasonable control, whether or not similar to those which are enumerated above.</p>
				<p>Savings Clause. If any part of these Terms is held invalid or unenforceable, that portion shall be construed in a manner consistent with applicable law to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect.</p>
				<p>No Waiver. Any failure by us to enforce or exercise any provision of these Terms or related rights shall not constitute a waiver of that right or provision.</p>
				<p>Entire Agreement. These terms and conditions constitute the entire agreement and understanding between the parties concerning the subject matter hereof and supersedes all prior agreements and understandings of the parties with respect thereto. These Terms may NOT be altered, supplemented, or amended by the use of any other document(s). To the extent that anything in or associated with this Site is in conflict or inconsistent with these Terms, these Terms shall take precedence.</p>
				</div>
			</article>
		</div>

		<?php
			require 'footer.php'
		?>
	</body>
</html>
